config/routes.rb
Rails.application.routes.draw do
  
  resources :networks

  resources :users
  resources :homes
  
  
  
  root 'application#not_found'
  
  
  
  
  get '/test' => 'homes#index'
  
  get '/cleaneventfile' => 'application#cleaneventfile'
  get '/exporteventfile' => 'application#exporteventfile'
  get '/geteventfile' => 'application#geteventfile'
  
  get '/cleanclickfile' => 'application#cleanclickfile'
  get '/exportclickfile' => 'application#exportclickfile'
  get '/getclickfile' => 'application#getclickfile'
  
  get '/cleanexportfile' => 'application#cleanexportfile'
  get '/cleanlogfile' => 'application#cleanlogfile'
  
  
  
  
  
  
  
  
  
  
  
  
  get '/getevent' => 'application#getevent'
  
  get '/get_event' => 'application#event'
  get '/event' => 'application#event'
  
  get '/getclick' => 'application#getclick'
  get '/click' => 'application#click'
  
  
  
  
  
    
  
  
  
  
  
  
   
  get '*unmatched_route' => 'application#not_found'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authuser, except: [:index,:demo,:contact_us,:send_demo_email,:send_contact_us_email]
  # before_action :loginuser, only: [:index]
  
  layout "application", :only => [ :index,:demo,:contact_us]  
  layout "home", :except => [ :index,:demo,:contact_us ] 
  
  require 'savon'
  require "azure"
  
  require 'rubygems'
  require 'mongo'
  
  # GET /homes
  # GET /homes.json
  
  def contact_us
      @title = " | Contact Us"
  end
  
  def demo
      @title = " | Request Demo"
  end
  
  def send_contact_us_email
      @contact_name = params[:contact_name]
      @contact_email = params[:contact_email]
      @contact_subject = params[:contact_subject]
      @contact_message = params[:contact_message]
      
      if @contact_name.to_s == "" || @contact_email.to_s == "" || @contact_subject.to_s == "" || @contact_message.to_s == ""
          data = {:message => "miss require field", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      
      begin
          mg_client = Mailgun::Client.new("key-63ad3b57013d96ecf8b581b02c917dbe")  
          mb_obj = Mailgun::MessageBuilder.new()
       
          mb_obj.set_from_address("do-not-reply@adeqo.com", {"first"=>"Adeqo", "last" => ""});
          
          
          # mb_obj.add_recipient(:cc, "bpo@bmgww.com", {"first" => "", "last" => ""});  
          mb_obj.add_recipient(:to, "adeqo@bmgww.com", {"first" => "", "last" => ""});
          mb_obj.add_recipient(:cc, "jkwan@bmgww.com", {"first" => "", "last" => ""});
          mb_obj.add_recipient(:cc, "xfung@bmgww.com", {"first" => "", "last" => ""});
          
          mb_obj.set_subject("Adeqo | Contact Us");  
          # mb_obj.set_text_body(result_msg);
          
          result_msg = "<p>Name:"+@contact_name+"</p>"
          result_msg = result_msg + "<p>Email:"+@contact_email+"</p>"
          result_msg = result_msg + "<p>Subject"+@contact_subject+"</p>"
          result_msg = result_msg + "<p>Message:<br /><br />"+@contact_message+"</p>"
          
           
          mb_obj.set_html_body(result_msg);
          mg_client.send_message("china.adeqo.com", mb_obj)
          
      rescue Exception
          data = {:message => "email error", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      data = {:message => "email done", :status => "true"}
      return render :json => data, :status => :ok
      
  end
  
  def send_demo_email
    
      @personal_demo_first_name = params[:personal_demo_first_name]
      @personal_demo_last_name = params[:personal_demo_last_name]
      @personal_demo_company_name = params[:personal_demo_company_name]
      @personal_demo_business_email = params[:personal_demo_business_email]
      @personal_demo_phone_number = params[:personal_demo_phone_number]
      @personal_demo_country = params[:personal_demo_country]
      @personal_demo_help = params[:personal_demo_help]
      
      if @personal_demo_first_name.to_s == "" || @personal_demo_last_name.to_s == "" || @personal_demo_business_email.to_s == ""
          data = {:message => "miss require field", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      begin
          
          mg_client = Mailgun::Client.new("key-63ad3b57013d96ecf8b581b02c917dbe")  
          mb_obj = Mailgun::MessageBuilder.new()
       
          mb_obj.set_from_address("do-not-reply@adeqo.com", {"first"=>"Adeqo", "last" => ""});
          
          mb_obj.add_recipient(:to, "adeqo@bmgww.com", {"first" => "", "last" => ""});
          mb_obj.add_recipient(:cc, "jkwan@bmgww.com", {"first" => "", "last" => ""});
          mb_obj.add_recipient(:cc, "xfung@bmgww.com", {"first" => "", "last" => ""});
          
          mb_obj.set_subject("Adeqo | Request Demo");  
          # mb_obj.set_text_body(result_msg);
          
          result_msg = "<p>First Name:"+@personal_demo_first_name+"</p>"
          result_msg = result_msg + "<p>Last Name:"+@personal_demo_last_name+"</p>"
          result_msg = result_msg + "<p>Company Name:"+@personal_demo_company_name+"</p>"
          result_msg = result_msg + "<p>Business Email:"+@personal_demo_business_email+"</p>"
          result_msg = result_msg + "<p>Phone Number:"+@personal_demo_phone_number+"</p>"
          result_msg = result_msg + "<p>Company:"+@personal_demo_country+"</p>"
          result_msg = result_msg + "<p>How can we help:<br /><br />"+@personal_demo_help+"</p>"
          
           
          mb_obj.set_html_body(result_msg);
          mg_client.send_message("china.adeqo.com", mb_obj)
          
      rescue Exception
          
          data = {:message => "email error", :status => "false"}
          return render :json => data, :status => :ok
      end
      
      data = {:message => "email done", :status => "true"}
      return render :json => data, :status => :ok
  end
  
  def index
    # @logger.info "Load Home index "+ @now.to_s
    loginuser()
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  
  def dashboard
  end


  def dashboarddetail
  end
  
  
  def getdashboard
    
      # @logger.info "Load Home getdashboard "+ @now.to_s
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @channel_array = params[:channel_array]
      @account_id_array = params[:account_array]
      
      if @channel_array.nil?
          @channel_array = []
      end
      
      if @end_date.nil?
          request_start_date = @today - 1.days
          @end_date = request_start_date.strftime("%Y-%m-%d")
      else
          session[:end_date] = @end_date.to_date
          @end_date = @end_date.to_date + 1.days
          @end_date = @end_date.strftime("%Y-%m-%d")
      end
      
      if @start_date.nil?
          request_start_date = @today - 8.days
          @start_date = request_start_date.strftime("%Y-%m-%d")
      else
          session[:start_date] = @start_date.to_date
          @start_date = @start_date.to_date
          @start_date = @start_date.strftime("%Y-%m-%d")
      end
      
      
      day_range = (@end_date.to_date - @start_date.to_date).to_i
      
      current_day = @today.strftime("%d")
      last_day = Date.today.end_of_month.strftime("%d")
      first_date_of_this_month = Date.today.at_beginning_of_month.strftime("%Y-%m-%d")
      
      @channels = []      
      @request_date = []
      
      @account = []
      
      @user_network_id_array = []
      @user_network_array = []
      
      if session[:user_network_id_array].nil?
        
          @user_network = @db[:network_user].find('user' => session[:user_id].to_i)
          @db.close
          
          @total_network_array = []
          
          @user_network.each do |user_network_d|
              @user_network_id_array << user_network_d["network_id"]
          end
          
          @total_network_array = @db[:network].find('id' => { "$in" => @user_network_id_array}, 'type' => { "$in" => @channel_array})
          @db.close
    
          if @total_network_array.count.to_i > 0
              @user_network_id_array = []
              
               @total_network_array.each do |total_network_array_d|
                  @user_network_id_array << total_network_array_d["id"]
               end
          end
          
          session[:user_network_id_array] = @user_network_id_array.join(",")
      else
          
          if @account_id_array.nil?
            
              @user_network_id_array = session[:user_network_id_array].split(",")
              @user_network_id_array = @user_network_id_array.map(&:to_i)
              
              @total_network_array = @db[:network].find('id' => { "$in" => @user_network_id_array}, 'type' => { "$in" => @channel_array})
              @db.close
              
          else
            
              @account_id_array = @account_id_array.map(&:to_i)
              @user_network_id_array = @account_id_array
              
              @total_network_array = @db[:network].find('id' => { "$in" => @account_id_array})
              @db.close
              
              session[:user_network_id_array] = @user_network_id_array.join(",")
          end
          
      end
          
      
      #account do same thing for other channel
      # session[:user_network_id_array] = nil
      
      
      if @start_date < first_date_of_this_month
        request_date_start_from = @start_date
      else
        request_date_start_from = first_date_of_this_month
      end
      
      @sogou_report_account = @db3[:sogou_report_account].find('network_id' => { "$in" => @user_network_id_array}, 'report_date' => { '$gte' => request_date_start_from.to_s }, 'display' => { "$gt" => 0})
      @db3.close
      
      @report_account_360 = @db3[:report_account_360].find('network_id' => { "$in" => @user_network_id_array}, 'report_date' => { '$gte' => request_date_start_from.to_s }, 'display' => { "$gt" => 0})
      @db3.close
      
      report_account_total_cost_hash = {}
      request_date_hash = {}
      
      # channels[]
      @sogou_object = {}
      @three_sixty_object = {}
      
      @sogou_impressions = 0
      @sogou_clicks = 0
      @sogou_ctr = 0
      @sogou_cost = 0
      @sogou_avg_cpc = 0
      @sogou_avg_pos = 0
      
      @three_sixty_impressions = 0
      @three_sixty_clicks = 0
      @three_sixty_ctr = 0
      @three_sixty_cost = 0
      @three_sixty_avg_cpc = 0
      @three_sixty_avg_pos = 0
      
      @conversion_sogou_count = 0
      @conversion_360_count = 0
      # channels[]
      
      # request date[]
      @request_end_date = params[:end_date].to_date + 1.days
      @request_date_array = []
      
      (1..day_range).each do |i|

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/contact_us.html.erb
<div class="adeqo-container page-contact-us">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container ">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="/" class="navbar-brand"><img src="/images/adeqo-logo.png" alt="Adeqo" title="Adeqo" width="132" height="76" class="img-responsive"/></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home</a></li>
            <li class="active"><a href="/contact_us">Contact Us</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <section class="banner">
    <h1>Contact Us</h1>
  </section>
  <section class="content">
    <div class="container">
      <div class="">
        <div class="col-xs-12 col-md-5 contact-us-left-col">
          <div id="msg"></div>
		  <form id="contact_us_form" method="post" class="form">
            <p>Call us at +852 2492 2770 or use below form to get in touch with us</p>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <input id="contact_name" name="contact_name" type="text" value="" class="form-control personal_form_text" placeholder="Name*"/>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <input id="contact_email" name="contact_email" type="text" value="" class="form-control personal_form_text" placeholder="Email*"/>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <input id="contact_subject" name="contact_subject" type="text" value="" class="form-control personal_form_text" placeholder="Subject*"/>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="contact_form_row">
              <div class="contact_form_input">
                <div class="form-group">
                  <textarea id="contact_message" name="contact_message" cols="40" rows="10" aria-invalid="false" class="form-control contact_form_text" placeholder="Message*"></textarea>
                </div><br/>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 horizontal-center">
                  <button type="button" id="submit_button" form="contact_us_form" class="button red_button submit_button">Send Your Message</button>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </form>
        </div>
        <div class="hidden-xs col-md-2"></div>
        <div class="col-xs-12 col-md-5">
          <div class="block-container">
            <h2><span class="contact_form_title">Visit Us:</span></h2>
            <p>Global Headquarters</p>
            <p>19/F, Tung Chiu Commercial Centre,<br/>193-197 Lockhart Road Wanchai, Hong Kong<br/>Tel: +852 2492 2770<br/>Email: <a href="mailto:sales@bmgww.com">sales@bmgww.com</a></p>
            <div>
              <button class="btn btn-default black-border" type="button" data-toggle="collapse" data-target="#collapseMap" aria-expanded="true" aria-controls="collapseMap">Get Direction</button>
              <div class="collapse in" id="collapseMap">
                <div style="height:400px; width: 100%;"> 
                  <div id="map"></div>
                </div> 
              </div>
            </div>
          </div>
          <div class="block-container">
            <h2><span class="contact_form_title">Join Us:</span></h2>
            <p>We're constantly looking for outstanding<br/>beings to join our team.</p>
            <p>Email us to find our more.</p>
            <a href="mailto:sales@bmgww.com" class="btn btn-default black-border">Join Us</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer class="footer-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <p>Copyright © 2016 Adeqo. <a href="http://www.bmgww.com" target="_blank">Intellectual Property of BMG</a>. All Rights Reserved.</p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <p class="text-right">Terms of use & Privacy Policy</p>
        </div>
      </div>
    </div>
  </footer>
</div>

<script type="text/javascript">


$("#submit_button").click(function(e){
	console.log("submit_button");
	
	var postData = $("#contact_us_form").serializeArray();
	var formURL = "/send_contact_us_email";
	
	$( "#msg" ).hide();
	$( "#msg" ).empty();
	$("#contact_us_form :input").prop("disabled", true);
	
	
	for (i = 0; i < postData.length; i++) {
		
		if(postData[i]["value"] == ""){
			$( "#msg" ).append( "<p style='color:red;'>Please fill in the required field.</p>" );
			$( "#msg" ).show();
			$("#contact_us_form :input").prop("disabled", false);
			return;
		}
		
		if(postData[i]["name"] == "contact_email"){
			var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if(regex.test(postData[i]["value"]) == false){
				$( "#msg" ).append( "<p style='color:red;'>Please make sure your email is in correct format.</p>" );
				$( "#msg" ).show();
				$("#contact_us_form :input").prop("disabled", false);
				return;		
			}
		}
	}
	
	
	$.ajax({
		url : formURL,
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR) 
		{
			if(data['status'] == "true"){
				$( "#msg" ).append( "<p style='color:green;'>Thanks for your email, we will reply to you shortly!</p>" );
				$( "#msg" ).show();
				$( "#contact_us_form" )[0].reset();
				$("#contact_us_form :input").prop("disabled", false);
				
				$( "#msg" ).delay(2500).slideUp(850);
			}else{
				$( "#msg" ).append( "<p style='color:red;'>Something wrong with your data, please make sure you type in the correct format.</p>" );
				$( "#msg" ).show();
				$("#contact_us_form :input").prop("disabled", false);
			}
		},
		error: function(jqXHR, textStatus, errorThrown) 
		{
			$( "#msg" ).append( "<p style='color:red;'>Our service is too busy, please try again in a few minutes.</p>" );
			$( "#msg" ).show();
			$("#contact_us_form :input").prop("disabled", false);
		}
	});
    e.preventDefault();
});
</script>

<script>
var map;
function initMap() {
  var myLatLng = {lat: 22.278503, lng: 114.1722743};

  // Create a map object and specify the DOM element for display.
  map = new google.maps.Map(document.getElementById('map'), {
    center: myLatLng,
    scrollwheel: false,
    zoom: 17
  });

  // Create a marker and set its position.
  var marker = new google.maps.Marker({
    map: map,
    position: myLatLng,
    title: '19/F, Tung Chiu Commercial Centre, 193-197 Lockhart Road, Wanchai, Hong Kong'
  });
}
</script>
<script async defer src="http://maps.google.cn/maps/api/js?key=&signed_in=false&amp;libraries=places&amp;language=en&amp;callback=initMap"></script>

app/views/homes/dashboarddetail.html.erb
<div class="content_title">Dashboard</div>
<ul class="tab_menu">
	<li><a class="tab_tag overview_tag" href="/dashboard">Overview</a></li>
	<li><a class="tab_tag details_tag active">Details</a></li>
</ul>
<div class="content_outer content-no-padding">

	<div class="content_core tab_content">
		<form action="" method="post" id="dashboardFilterForm" autocomplete="off">
			<ul class="nav nav-pills filters-nav">
				<!-- <li class="dropdown" id="custom-view-dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button">
						<img src="/images/icon/custom.png" alt="Custom" title="Custom">
						Custom View <span class="caret"></span>
					</a>-->
					<!-- <ul class="dropdown-menu">
					</ul> -->
				<!--</li> -->
	
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button">
						<img src="/images/icon/network.png" alt="Networks" title="Networks"> Network Filter <span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="javascript:;">
							<label for="qihoo_360" class="normal-font-weight">
								<input type="checkbox" id="qihoo_360" name="channel_array[]" value="360" checked> Qihoo 360
							</label>
						</a></li>
						<!-- <li><a href="javascript:;">
							<label for="baidu" class="normal-font-weight">
								<input type="checkbox" id="baidu" name="channel_array" value="checked"> Baidu
							</label>
						</a></li>
						<li><a href="javascript:;">
							<label for="shenma" class="normal-font-weight">
								<input type="checkbox" id="shenma" name="channel_array" value="checked"> Shenma
							</label>
						</a></li> -->
						<li><a href="javascript:;">
							<label for="sogou" class="normal-font-weight">
								<input type="checkbox" id="sogou" name="channel_array[]" value="sogou" checked> Sogou
							</label>
						</a></li>
						<li>
							<a class="no-highlight">
								<button type="button" class="btn btn-red btn-xs btn-halfwidth" onclick="applyFilter(this, true);">Apply</button>
								<button type="button" class="btn btn-white btn-xs btn-halfwidth" onclick="applyFilter(this, false);">Cancel</button>
							</a>
						</li>
					</ul>
				</li>
	
				<li class="dropdown" id="custom-view-dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button">
						<img src="/images/icon/account.png" alt="Account Filter" title="Account Filter">
						Account Filter <span class="caret"></span>
					</a>
					<ul class="dropdown-menu">

						<%
						
						@user_network_id_array = []
				      	@user_network = @db[:network_user].find('user' => session[:user_id].to_i)
				      
				      	@user_network.each do |user_network|
				        	@user_network_id_array << user_network["network_id"]
				      	end
				      	
				      	@current_user_network = @db[:network].find('id' => { "$in" => @user_network_id_array})
						%>
						
						<%
						all_checkbox_checked = false
						if @current_user_network.count.to_i > 0
				        	@current_user_network.each do |network|
		            		%>
		            		<li>
		            			<a href="javascript:;">
								<label for="<%=network["type"].to_s%>_<%=network["name"].to_s%>" class="normal-font-weight">
									<input type="checkbox" class="account_id" id="<%=network["type"].to_s%>_<%=network["id"].to_i%>" name="account_array[]" value="<%=network["id"].to_i%>" > <%=network["name"].to_s%>
								</label>
								</a>
							</li>
		            		<%
				            end
				        end	
						%>
						
						<li>
							<a class="no-highlight">
								<label for="all" class="normal-font-weight">
									<% if all_checkbox_checked %>
										<input type="checkbox" id="all" checked onchange="selectAllFilterAccountOption(this);"> All
									<% else %>
										<input type="checkbox" id="all" onchange="selectAllFilterAccountOption(this);">
									<% end %>
								</label>
								<button type="button" class="btn btn-red btn-xs" onclick="applyFilter(this, true);">Apply</button>
								<button type="button" class="btn btn-white btn-xs" onclick="applyFilter(this, false);">Cancel</button>
							</a>
						</li>
					</ul>
				</li>
				
				<li class="pull-right">
					<a onclick="$('#date-range-dropdown .dropdown-toggle').dropdown('toggle');" href="javascript:;">
						<span class="caret"></span>
						<img src="/images/icon/calendar.png" alt="Networks" title="Networks">
					</a>
				</li>
				<li id="date-range-dropdown" class="dropdown pull-right">
					<a class="dropdown-toggle" data-toggle="dropdown" href="javascript:;" role="button">
						<div class="text-right date-range">
							Last 7 days<br>
							10 June 2015 - 16 June 2015
						</div>
					</a>
					<ul class="dropdown-menu">
						<li class="text-center" onclick="setDate('Yesterday');applyFilter(this);"><a href="javascript:;">Yesterday</a></li>
						<li class="text-center" onclick="setDate('Last 7 days');applyFilter(this);"><a href="javascript:;">Last 7 days</a></li>
						<li class="text-center" onclick="setDate('Last 30 days');applyFilter(this);"><a href="javascript:;">Last 30 days</a></li>
						<li class="text-center" onclick="setDate('This Week');applyFilter(this);"><a href="javascript:;">This Week</a></li>
						<li class="text-center" onclick="setDate('Last Week');applyFilter(this);"><a href="javascript:;">Last Week</a></li>
						<li class="text-center" onclick="setDate('This Month');applyFilter(this);"><a href="javascript:;">This Month</a></li>
						<li class="text-center" onclick="setDate('Last Month');applyFilter(this);"><a href="javascript:;">Last Month</a></li>
						<li class="text-center" onclick="setDate('Last 3 Months');applyFilter(this);"><a href="javascript:;">Last 3 Months</a></li>
						<li class="text-center"><a class="no-highlight">Select Dates:</a></li>
						<li class="text-center">
							<a class="no-highlight">
								<div class="datepicker-container">
									<input type="text" id="start_date" name="start_date" class="datepicker-field">
									<span class="caret input-caret"></span>
								</div>
							</a>
							to
							<a class="no-highlight">
								<div class="datepicker-container">
									<input type="text" id="end_date" name="end_date" class="datepicker-field">
									<span class="caret input-caret"></span>
								</div>
							</a>
						</li>
						<li class="text-center">
							<a class="no-highlight" href="javascript:;">
								<button type="button" class="btn btn-red btn-xs btn-fullwidth" onclick="applyFilter(this, true);">Apply</button>
							</a>
						</li>
					</ul>
				</li>
	
			</ul>
		</form>
	</div>

</div>

<div class="line-chart-container">

	<div class="line-chart-legend-container">
		<span class="line-chart-legend line-chart-legend-1"></span>
		<span class="line-chart-dropdown-container">
			<select id="line-chart-dropdown-1" class="chosen-select" onchange="genLineChart(this.value, $('#line-chart-dropdown-2').val());">
				<option value="">None</option>
				<option value="impressions" selected>Impr.</option>
				<option value="clicks">Clicks</option>
				<option value="ctr">CTR</option>
				<option value="cost">Cost</option>
				<option value="avg_cpc">Avg. CPC</option>
				<option value="conversion">Conversions</option>
				<option value="conversion_rate">Conv. Rate</option>
				<option value="cpa">CPA</option>
				<option value="revenue">Revenue</option>
				<option value="profit">Profit</option>
				<option value="avg_pos">Avg. Pos.</option>
			</select>
		</span>

		<span class="line-chart-legend line-chart-legend-2"></span>
		<span class="line-chart-dropdown-container">
			<select id="line-chart-dropdown-2" class="chosen-select" onchange="genLineChart($('#line-chart-dropdown-1').val(), this.value);">
				<option value="">None</option>
				<option value="impressions">Impr.</option>
				<option value="clicks" selected>Clicks</option>
				<option value="ctr">CTR</option>
				<option value="cost">Cost</option>
				<option value="avg_cpc">Avg. CPC</option>
				<option value="conversion">Conversions</option>
				<option value="conversion_rate">Conv. Rate</option>
				<option value="cpa">CPA</option>
				<option value="revenue">Revenue</option>
				<option value="profit">Profit</option>
				<option value="avg_pos">Avg. Pos.</option>
			</select>
		</span>
	</div>

	<canvas id="line-chart"></canvas>
</div>

<div id="details-table-container">
	<table id="details-table" class="table table-condensed">
		<thead>
			<tr>
				<th>Date</th>
				<th>Impr.</th>
				<th>Clicks</th>
				<th>CTR</th>
				<th>Cost</th>
				<th>Avg. CPC</th>
				<th>Conversions</th>
				<th>Conv. Rate</th>
				<th>CPA</th>
				<th>Revenue</th>
				<th>Profit</th>
				<th>Avg. Pos.</th>
			</tr>
		</thead>
		<tbody class="text-right">
			
		</tbody>
	</table>
	<!-- following element will be moved into .dataTables_wrapper by js -->
	<!-- <div class="datatables-legend-container">
		<span class="datatables-legend label below-budget">&nbsp;</span>
		<span class="datatables-legend-text">Under Budget</span>
		<span class="datatables-legend label on-budget">&nbsp;</span>
		<span class="datatables-legend-text">On Budget</span>
		<span class="datatables-legend label over-budget">&nbsp;</span>
		<span class="datatables-legend-text">Over Budget</span>
	</div> -->
</div>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>